import React, { useMemo } from "react";

const LKR = (n) =>
  new Intl.NumberFormat("en-LK", {
    style: "currency",
    currency: "LKR",
    maximumFractionDigits: 0,
  }).format(Number(n || 0));

export default function SalarySlipGenerator({ employee, input, payroll, onClose }) {
  const isMonthly = payroll.isMonthly;
  const isDaily = payroll.isDaily;

  const slipNo = useMemo(() => {
    const base = payroll.period.mode === "Monthly"
      ? payroll.period.value.replace("-", "")
      : payroll.period.mode === "Weekly"
      ? payroll.period.value.replace("-", "")
      : payroll.period.value.replaceAll("-", "");
    return `SLIP-${base}-${employee.employeeID}`;
  }, [payroll.period, employee.employeeID]);

  const att = input?.attendance || {};

  const onPrint = () => window.print();

  return (
    <div style={styles.overlay} onMouseDown={onClose}>
      <div style={styles.modal} onMouseDown={(e) => e.stopPropagation()}>
        <div style={styles.header}>
          <div>
            <div style={styles.title}>Salary Slip</div>
            <div style={styles.sub}>
              Kulasekara Oil Mills • Period: <b>{payroll.period.label}</b>
            </div>
          </div>
          <div style={styles.actions}>
            <button style={styles.btn} onClick={onPrint}>Print</button>
            <button style={styles.btnSecondary} onClick={onClose}>Close</button>
          </div>
        </div>

        {/* Print Area */}
        <div id="slip-print-area" style={styles.sheet}>
          <div style={styles.sheetHeader}>
            <div>
              <div style={styles.company}>Kulasekara Oil Mills</div>
              <div style={styles.sheetMeta}>Salary Slip • {payroll.period.label}</div>
            </div>
            <div style={styles.rightMeta}>
              <div><b>Slip No:</b> {slipNo}</div>
              <div><b>Date:</b> {new Date().toISOString().slice(0, 10)}</div>
            </div>
          </div>

          <div style={styles.infoGrid}>
            <Info label="Employee ID" value={employee.employeeID} />
            <Info label="Employee Name" value={employee.name} />
            <Info label="Department" value={employee.department} />
            <Info label="Salary Type" value={employee.salaryType} />
            <Info label="Period" value={payroll.period.label} />
            <Info label="Attendance" value={`${att.presentDays ?? 0} Present, ${att.absentDays ?? 0} Absent`} />
          </div>

          <div style={styles.breakdownGrid}>
            <div style={styles.card}>
              <div style={styles.cardTitle}>Earnings</div>

              {isMonthly ? (
                <Line label="Base Salary (Monthly)" value={LKR(payroll.basePay)} />
              ) : (
                <>
                  <Line label="Task Earnings (Period)" value={LKR(payroll.taskEarnings)} />
                  <div style={styles.note}>
                    {isDaily ? "Daily wage: task-based (NO overtime)." : "Weekly wage: task-based + overtime (if any)."}
                  </div>
                </>
              )}

              {!isDaily && <Line label="Overtime" value={LKR(payroll.overtimeTotal)} />}

              <Line label="Incentives" value={LKR(payroll.incentiveTotal)} />
              <Line label="Allowances" value={LKR(payroll.allowanceTotal)} />

              <hr style={styles.hr} />
              <Line label="Gross Pay" value={LKR(payroll.gross)} strong />
            </div>

            <div style={styles.card}>
              <div style={styles.cardTitle}>Deductions</div>

              {isMonthly ? (
                <>
                  <Line label="EPF (Employee)" value={LKR(payroll.epfEmployee)} />
                  <div style={styles.note}>
                    Employer side: EPF {LKR(payroll.employerEPF)} • ETF {LKR(payroll.employerETF)}
                  </div>
                </>
              ) : (
                <div style={styles.note}>EPF/ETF deductions apply only for monthly employees.</div>
              )}

              <Line label="Other Deductions" value={LKR(payroll.otherDeductions)} />
              <hr style={styles.hr} />
              <Line label="Total Deductions" value={LKR(payroll.totalDeductions)} />
              <Line label="Net Pay" value={LKR(payroll.net)} strong />
            </div>
          </div>

          <div style={styles.footerRow}>
            <div style={styles.signatureBox}>
              <div style={styles.sigLine} />
              <div style={styles.sigLabel}>Employee Signature</div>
            </div>

            <div style={styles.signatureBox}>
              <div style={styles.sigLine} />
              <div style={styles.sigLabel}>Authorized Signature</div>
            </div>
          </div>

          <div style={styles.smallNote}>
            Generated by Payroll System • Keep this slip for your records.
          </div>
        </div>
      </div>

      {/* Print CSS */}
      <style>{`
        @media print {
          body * { visibility: hidden !important; }
          #slip-print-area, #slip-print-area * { visibility: visible !important; }
          #slip-print-area { position: absolute; left: 0; top: 0; width: 100%; }
        }
      `}</style>
    </div>
  );
}

function Info({ label, value }) {
  return (
    <div style={styles.info}>
      <div style={styles.infoLabel}>{label}</div>
      <div style={styles.infoValue}>{value}</div>
    </div>
  );
}

function Line({ label, value, strong }) {
  return (
    <div style={styles.line}>
      <div style={styles.lineLabel}>{label}</div>
      <div style={{ ...styles.lineValue, ...(strong ? { fontWeight: 900 } : {}) }}>{value}</div>
    </div>
  );
}

const styles = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "grid",
    placeItems: "center",
    padding: 14,
    zIndex: 60,
  },
  modal: {
    width: "min(980px, 96vw)",
    maxHeight: "90vh",
    overflow: "auto",
    background: "white",
    borderRadius: 16,
    boxShadow: "0 20px 60px rgba(0,0,0,0.25)",
    border: "1px solid rgba(0,0,0,0.08)",
  },
  header: {
    padding: 14,
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    borderBottom: "1px solid rgba(0,0,0,0.08)",
  },
  title: { fontWeight: 900, fontSize: 16 },
  sub: { marginTop: 4, fontSize: 12, opacity: 0.75 },
  actions: { display: "flex", gap: 10, alignItems: "center" },
  btn: {
    height: 38,
    borderRadius: 10,
    border: "none",
    background: "#FBBF24",
    padding: "0 14px",
    fontWeight: 900,
    cursor: "pointer",
  },
  btnSecondary: {
    height: 38,
    borderRadius: 10,
    border: "1px solid rgba(0,0,0,0.14)",
    background: "white",
    padding: "0 14px",
    fontWeight: 900,
    cursor: "pointer",
  },

  sheet: { padding: 18 },
  sheetHeader: { display: "flex", justifyContent: "space-between", gap: 12, marginBottom: 14 },
  company: { fontSize: 18, fontWeight: 900 },
  sheetMeta: { opacity: 0.75, marginTop: 2 },
  rightMeta: { textAlign: "right", fontSize: 12, opacity: 0.9 },

  infoGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 10, marginBottom: 14 },
  info: { border: "1px solid rgba(0,0,0,0.08)", borderRadius: 12, padding: 10, background: "white" },
  infoLabel: { fontSize: 12, opacity: 0.7, fontWeight: 800 },
  infoValue: { marginTop: 4, fontWeight: 900 },

  breakdownGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12 },
  card: { border: "1px solid rgba(0,0,0,0.08)", borderRadius: 14, padding: 12, background: "white" },
  cardTitle: { fontWeight: 900, marginBottom: 10 },
  line: { display: "flex", justifyContent: "space-between", gap: 12, padding: "6px 0" },
  lineLabel: { opacity: 0.75, fontWeight: 800 },
  lineValue: { fontWeight: 800 },
  hr: { border: "none", borderTop: "1px solid rgba(0,0,0,0.08)", margin: "10px 0" },
  note: { marginTop: 8, fontSize: 12, opacity: 0.7 },

  footerRow: { marginTop: 18, display: "flex", justifyContent: "space-between", gap: 14 },
  signatureBox: { flex: 1, textAlign: "center" },
  sigLine: { height: 1, background: "rgba(0,0,0,0.35)", margin: "26px 18px 8px" },
  sigLabel: { fontSize: 12, opacity: 0.75, fontWeight: 800 },

  smallNote: { marginTop: 12, fontSize: 12, opacity: 0.7 },
};
